### ISSUE TITLE
Add network connection activity to the DLL Side-loading micro plan

### ISSUE THREAD

**Issue by Cyb3r-Monk** [center-for-threat-informed-defense/adversary_emulation_library#129]
It would be great if `DLL Side-loading` micro plan contain few HTTP requests to a legitimate website (as a parameter or embedded in the code) to simulate C2 behavior.

**Comment by mticmtic** [comment]
Hi @Cyb3r-Monk, our original intent was to capture the side-loading and any follow on behavior (discovery commands, in this instance). The specifics of the follow on behavior isn't as important as the combination of side-loading and the follow on behavior. With that said, we will add it to the backlog and see if we can get to it soon.

**Comment by cat-alyst** [comment]
Added this to the backlog, going to close this issue. @Cyb3r-Monk Thank you for the suggestion! 🤩  We will tag you in the PR for contribution credit.

**Comment by Cyb3r-Monk** [comment]
Awesome, thanks! 🤩
