### ISSUE TITLE
controlServer for Turla emulation plan

### ISSUE THREAD

**Issue by xuanxuan0** [center-for-threat-informed-defense/adversary_emulation_library#143]
I can't find the "controlServer" executable under Resources/control_server for the Turla plan. Could you please add it?

**Comment by cat-alyst** [comment]
In efforts to start removing executables inside the GitHub repo we decided to drop the executable. There are instructions to build the control server [here](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/turla/Resources/control_server#build-from-source).
