### ISSUE TITLE
Versioning and Change log for Each Plan

### ISSUE THREAD

**Issue by jcwilliamsATmitre** [center-for-threat-informed-defense/adversary_emulation_library#15]
Good idea from Jon to track the version number on each individual plan, we can also make a separate change log file for each adversary

**Comment by jcwilliamsATmitre** [comment]
Partially addressed by @forrestcarver - https://github.com/center-for-threat-informed-defense/adversary_emulation_library/commit/3bd44af1f5b76d820362cbc50f520d06706fb55c

**Comment by jwbaker-mitre** [comment]
This has been resolved with the individual changes logs in each plan, as well as the official release versioning for the overall Center Library recently implemented. https://github.com/center-for-threat-informed-defense/adversary_emulation_library/releases
