### ISSUE TITLE
Invalid Powershell syntax

### ISSUE THREAD

**Issue by shinsugarfj** [center-for-threat-informed-defense/adversary_emulation_library#19]
Hi, 
I found 10 occurrences of `{else 1}` in FIN6.yaml (in lines 43, 90, ...). Not much of an impact, but I think those should be `{exit 1}`.

https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/0fd544e0382d8dfbc4bd2e1e51ba8227eccd88fd/fin6/Emulation_Plan/FIN6.yaml#L43

**Comment by jwbaker-mitre** [comment]
The typo has been corrected.  Thank you for your feedback!
