### ISSUE TITLE
Ransomeware -> Ransomware

### ISSUE THREAD

**Issue by Cyb3rWard0g** [center-for-threat-informed-defense/adversary_emulation_library#29]
I was reading line by line and I found this also:

Ransomeware
* https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/FIN6.yaml#L949
* https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/FIN6.yaml#L1018

I have made the same mistake when typing that word a lot :) I believe it should be `Ransomware`.

**Comment by jwbaker-mitre** [comment]
Corrected.  Thank you for your feedback! @Cyb3rWard0g
