### ISSUE TITLE
Wrong command to get AD subnet information

### ISSUE THREAD

**Issue by shinsugarfj** [center-for-threat-informed-defense/adversary_emulation_library#32]
I believe I caught an error in the command of FIN6: e4cdb5c6-d322-3b6e-ac8e-68b2e8a7dd4c.

~~~
adfind.exe -gcb -sc trustdmp > ad_subnets.txt`
~~~

should be 

~~~
adfind.exe -subnets -f (objectCategory=subnet) > ad_subnets.txt`
~~~

in order to get the correct results.

**Comment by jwbaker-mitre** [comment]
Thank you for finding this error.  It has been corrected in the most recent commit.
